
services:

  web:

    healthcheck:

      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]

      interval: 30s

      timeout: 10s

      retries: 3

      start_period: 20s


  worker:

    depends_on:

      web:

        condition: service_healthy

      redis:

        condition: service_started


  beat:

    depends_on:

      web:

        condition: service_healthy

      redis:

        condition: service_started

