
services:
  redis:
    image: redis:7-alpine
    container_name: montalaq_redis
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - redis-data:/data
    networks: [montalaq]
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: montalaq_web
    env_file:
      - .env
    environment:
      # Sensible defaults if not set in .env
      REDIS_URL: ${REDIS_URL:-redis://redis:6379/0}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL:-redis://redis:6379/0}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND:-redis://redis:6379/0}
      SQLITE_PATH: ${SQLITE_PATH:-/app/data/db.sqlite3}
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE:-montalaq_project.settings}
      DEBUG: ${DEBUG:-1}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS:-*}
      PORT: ${PORT:-8000}
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - .:/app
      - sqlite-data:/app/data
    ports:
      - "8000:8000"
    networks: [montalaq]
    entrypoint:
      - /app/docker/entrypoint.web.sh
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: montalaq_worker
    env_file:
      - .env
    environment:
      REDIS_URL: ${REDIS_URL:-redis://redis:6379/0}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL:-redis://redis:6379/0}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND:-redis://redis:6379/0}
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE:-montalaq_project.settings}
      CELERY_CONCURRENCY: ${CELERY_CONCURRENCY:-4}
    depends_on:
      redis:
        condition: service_healthy
      web:
        condition: service_started
    volumes:
      - .:/app
      - sqlite-data:/app/data
    networks: [montalaq]
    entrypoint:
      - /app/docker/entrypoint.worker.sh
  beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: montalaq_beat
    env_file:
      - .env
    environment:
      REDIS_URL: ${REDIS_URL:-redis://redis:6379/0}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL:-redis://redis:6379/0}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND:-redis://redis:6379/0}
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE:-montalaq_project.settings}
    depends_on:
      redis:
        condition: service_healthy
      web:
        condition: service_started
    volumes:
      - .:/app
      - beat-schedule:/app/celerybeat
    networks: [montalaq]
    entrypoint:
      - /app/docker/entrypoint.beat.sh
volumes:
  redis-data:
  sqlite-data:
  beat-schedule:
networks:
  montalaq:
    driver: bridge
