# Generated by Django 5.2.5 on 2025-08-09 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('symbol', models.CharField(max_length=20)),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.FloatField()),
                ('provider', models.CharField(max_length=50)),
            ],
            options={
                'indexes': [models.Index(fields=['symbol', 'timestamp'], name='backend_mar_symbol_53af12_idx')],
                'unique_together': {('timestamp', 'symbol')},
            },
        ),
        migrations.CreateModel(
            name='MarketDataFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atr_14', models.FloatField(blank=True, null=True)),
                ('ema_8', models.FloatField(blank=True, null=True)),
                ('ema_20', models.FloatField(blank=True, null=True)),
                ('ema_50', models.FloatField(blank=True, null=True)),
                ('rsi_14', models.FloatField(blank=True, null=True)),
                ('bb_bbm', models.FloatField(blank=True, null=True)),
                ('bb_bbh', models.FloatField(blank=True, null=True)),
                ('bb_bbl', models.FloatField(blank=True, null=True)),
                ('bb_bandwidth', models.FloatField(blank=True, null=True)),
                ('vwap', models.FloatField(blank=True, null=True)),
                ('vwap_dist', models.FloatField(blank=True, null=True)),
                ('volume_zscore', models.FloatField(blank=True, null=True)),
                ('range_atr_ratio', models.FloatField(blank=True, null=True)),
                ('ema_bull_cross', models.BooleanField(default=False)),
                ('ema_bear_cross', models.BooleanField(default=False)),
                ('rsi_overbought', models.BooleanField(default=False)),
                ('rsi_oversold', models.BooleanField(default=False)),
                ('bb_squeeze', models.BooleanField(default=False)),
                ('market_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='backend.marketdata')),
            ],
        ),
        migrations.CreateModel(
            name='TradeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ml_signal', models.CharField(blank=True, max_length=20, null=True)),
                ('ml_prob_long', models.FloatField(blank=True, null=True)),
                ('ml_prob_short', models.FloatField(blank=True, null=True)),
                ('ml_prob_no_trade', models.FloatField(blank=True, null=True)),
                ('ml_expected_rr', models.FloatField(blank=True, null=True)),
                ('ml_model_version', models.CharField(blank=True, max_length=50, null=True)),
                ('entry_price', models.FloatField(blank=True, null=True)),
                ('stop_loss', models.FloatField(blank=True, null=True)),
                ('take_profit', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('market_data_feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_analysis', to='backend.marketdatafeatures')),
            ],
        ),
        migrations.AddIndex(
            model_name='marketdatafeatures',
            index=models.Index(fields=['market_data'], name='backend_mar_market__a99631_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='marketdatafeatures',
            unique_together={('market_data',)},
        ),
        migrations.AddIndex(
            model_name='tradeanalysis',
            index=models.Index(fields=['ml_signal'], name='backend_tra_ml_sign_d3f017_idx'),
        ),
        migrations.AddIndex(
            model_name='tradeanalysis',
            index=models.Index(fields=['ml_model_version'], name='backend_tra_ml_mode_adbfb3_idx'),
        ),
    ]
