# Generated by Django 5.2.5 on 2025-08-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=50)),
                ('training_date', models.DateTimeField(auto_now_add=True)),
                ('parameters', models.JSONField()),
                ('metrics', models.JSONField()),
            ],
        ),
    ]
