# Generated by Django 5.2.5 on 2025-08-12 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_modelmetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeanalysis',
            name='candlestick_pattern',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tradeanalysis',
            name='confluence_ok',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tradeanalysis',
            name='final_decision',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tradeanalysis',
            name='indicator_confluence',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tradeanalysis',
            name='pattern_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tradeanalysis',
            name='pattern_location_sr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tradeanalysis',
            name='proximity_to_sr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tradeanalysis',
            name='rule_confidence_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradeanalysis',
            name='volume_support',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='tradeanalysis',
            index=models.Index(fields=['final_decision'], name='backend_tra_final_d_1eab07_idx'),
        ),
    ]
