# Generated by Django 5.2.5 on 2025-08-14 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_tradeanalysis_candlestick_pattern_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeanalysis',
            name='composite_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradeanalysis',
            name='feature_importances',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradeanalysis',
            name='ml_model_hash_prefix',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
