# Generated by Django 5.2.5 on 2025-08-16 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_add_agent011_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeanalysis',
            name='ml_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradeanalysis',
            name='top_features',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
