# Generated by Django 5.2.5 on 2025-08-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_tradeanalysis_ml_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeanalysis',
            name='timestamp',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='tradeanalysis',
            index=models.Index(fields=['timestamp'], name='backend_tra_timesta_a54992_idx'),
        ),
    ]
