# Generated by Django 5.2.5 on 2025-08-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_timeframe_and_tradeanalysis_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='MlPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('float_value', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='marketdata',
            name='backend_mar_symbol_53af12_idx',
        ),
        migrations.RemoveIndex(
            model_name='tradeanalysis',
            name='backend_tra_ml_sign_d3f017_idx',
        ),
        migrations.RemoveIndex(
            model_name='tradeanalysis',
            name='ta_mdf_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='marketdata',
            new_name='backend_mar_symbol_db0337_idx',
            old_name='md_symtf_ts_idx',
        ),
        migrations.AlterUniqueTogether(
            name='marketdatafeatures',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tradeanalysis',
            name='ml_skipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tradeanalysis',
            name='rule_confidence_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='symbol',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='timeframe',
            field=models.CharField(db_index=True, default='1m', max_length=10),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='timestamp',
            field=models.DateTimeField(db_index=True),
        ),
    ]
