# Generated by Django 5.2.5 on 2025-08-21 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_mlpreference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('timeframe', models.CharField(db_index=True, max_length=10)),
                ('bar_ts', models.DateTimeField(db_index=True)),
                ('state', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngestionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('timeframe', models.CharField(db_index=True, max_length=10)),
                ('last_bar_ts', models.DateTimeField(blank=True, null=True)),
                ('last_ingest_ts', models.DateTimeField(blank=True, null=True)),
                ('freshness_state', models.CharField(choices=[('GREEN', 'Green'), ('AMBER', 'Amber'), ('RED', 'Red')], default='RED', max_length=10)),
                ('data_freshness_sec', models.IntegerField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, max_length=50, null=True)),
                ('key_age_days', models.IntegerField(blank=True, null=True)),
                ('fallback_active', models.BooleanField(default=False)),
                ('analyses_ok_5m', models.IntegerField(default=0)),
                ('analyses_fail_5m', models.IntegerField(default=0)),
                ('median_latency_ms', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='tradeanalysis',
            name='error_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tradeanalysis',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradeanalysis',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradeanalysis',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradeanalysis',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='tradeanalysis',
            index=models.Index(fields=['status'], name='backend_tra_status_d81a98_idx'),
        ),
        migrations.AddIndex(
            model_name='analysislog',
            index=models.Index(fields=['symbol', 'timeframe', 'bar_ts'], name='backend_ana_symbol_0f1563_idx'),
        ),
        migrations.AddIndex(
            model_name='analysislog',
            index=models.Index(fields=['state'], name='backend_ana_state_049b28_idx'),
        ),
        migrations.AddIndex(
            model_name='ingestionstatus',
            index=models.Index(fields=['symbol', 'timeframe'], name='backend_ing_symbol_e2acc0_idx'),
        ),
        migrations.AddIndex(
            model_name='ingestionstatus',
            index=models.Index(fields=['freshness_state'], name='backend_ing_freshne_8a19e4_idx'),
        ),
    ]
