# Generated by Django 5.2.5 on 2025-08-22 21:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_analysislog_ingestionstatus_tradeanalysis_error_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MlModelRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(db_index=True, max_length=100)),
                ('version', models.CharField(max_length=50)),
                ('hash_prefix', models.CharField(max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('channel_type', models.CharField(choices=[('EMAIL', 'EMAIL'), ('WEBHOOK', 'WEBHOOK'), ('SLACK', 'SLACK')], max_length=16)),
                ('enabled', models.BooleanField(default=False)),
                ('min_severity', models.CharField(default='INFO', max_length=10)),
                ('config', models.JSONField(default=dict)),
                ('events', models.JSONField(default=dict)),
                ('dedupe_window_sec', models.IntegerField(default=900)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ModelMetadata',
        ),
        migrations.AddField(
            model_name='ingestionstatus',
            name='breaker_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ingestionstatus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingestionstatus',
            name='escalation_level',
            field=models.CharField(choices=[('INFO', 'INFO'), ('WARN', 'WARN'), ('ERROR', 'ERROR'), ('CRITICAL', 'CRITICAL')], default='INFO', max_length=10),
        ),
        migrations.AddField(
            model_name='ingestionstatus',
            name='last_notify_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingestionstatus',
            name='last_signal_bar_ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingestionstatus',
            name='freshness_state',
            field=models.CharField(choices=[('GREEN', 'GREEN'), ('AMBER', 'AMBER'), ('RED', 'RED')], default='GREEN', max_length=10),
        ),
        migrations.AlterField(
            model_name='ingestionstatus',
            name='provider',
            field=models.CharField(choices=[('AllTick', 'AllTick'), ('TwelveData', 'TwelveData')], default='AllTick', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='ingestionstatus',
            unique_together={('symbol', 'timeframe')},
        ),
        migrations.AddIndex(
            model_name='ingestionstatus',
            index=models.Index(fields=['escalation_level'], name='backend_ing_escalat_f2e038_idx'),
        ),
        migrations.AddIndex(
            model_name='mlmodelregistry',
            index=models.Index(fields=['model_name', 'version'], name='backend_mlm_model_n_33362e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mlmodelregistry',
            unique_together={('model_name', 'version')},
        ),
    ]
