# backend/migrations/0012_remove_tradeanalysis_backend_tra_timesta_a54992_idx_and_more.py
# Generated by Django 5.2.5 on 2025-08-23 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_mlmodelregistry_notificationchannel_and_more'),
    ]

    operations = [
        # 0) Drop the old index that referenced timestamp
        migrations.RemoveIndex(
            model_name='tradeanalysis',
            name='backend_tra_timesta_a54992_idx',
        ),

        # 1) Add/alter fields required by 013.4
        migrations.AddField(
            model_name='ingestionstatus',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradeanalysis',
            name='symbol',
            field=models.CharField(blank=True, null=True, db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='tradeanalysis',
            name='timeframe',
            field=models.CharField(blank=True, null=True, db_index=True, max_length=10),
        ),
        migrations.AddField(
            model_name='tradeanalysis',
            name='bar_ts',
            field=models.DateTimeField(blank=True, null=True, db_index=True),
        ),
        migrations.AddField(
            model_name='tradeanalysis',
            name='sl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradeanalysis',
            name='tp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='provider',
            field=models.CharField(default='AllTick', max_length=50),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='timeframe',
            field=models.CharField(max_length=10, db_index=True),
        ),
        migrations.AlterField(
            model_name='tradeanalysis',
            name='market_data_feature',
            field=models.ForeignKey(
                to='backend.marketdatafeatures',
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='trade_analyses',
            ),
        ),

        # 2) NOW switch the uniqueness contract to the new key (before removing old fields)
        migrations.AlterUniqueTogether(
            name='tradeanalysis',
            unique_together={('symbol', 'timeframe', 'bar_ts')},
        ),

        # 3) Add the composite index on the new key trio
        migrations.AddIndex(
            model_name='tradeanalysis',
            index=models.Index(
                fields=['symbol', 'timeframe', 'bar_ts'],
                name='backend_tra_symbol_7a7e4d_idx',
            ),
        ),

        # 4) Remove legacy fields (timestamp and other old schema fields)
        migrations.RemoveField(model_name='tradeanalysis', name='candlestick_pattern'),
        migrations.RemoveField(model_name='tradeanalysis', name='confluence_ok'),
        migrations.RemoveField(model_name='tradeanalysis', name='entry_price'),
        migrations.RemoveField(model_name='tradeanalysis', name='feature_importances'),
        migrations.RemoveField(model_name='tradeanalysis', name='indicator_confluence'),
        migrations.RemoveField(model_name='tradeanalysis', name='pattern_confirmed'),
        migrations.RemoveField(model_name='tradeanalysis', name='pattern_location_sr'),
        migrations.RemoveField(model_name='tradeanalysis', name='proximity_to_sr'),
        migrations.RemoveField(model_name='tradeanalysis', name='rule_confidence'),
        migrations.RemoveField(model_name='tradeanalysis', name='stop_loss'),
        migrations.RemoveField(model_name='tradeanalysis', name='take_profit'),
        migrations.RemoveField(model_name='tradeanalysis', name='timestamp'),
        migrations.RemoveField(model_name='tradeanalysis', name='volume_support'),
    ]
