# Generated by Django 5.2.5 on 2025-08-23 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_enforce_tradeanalysis_keys_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeanalysis',
            name='bar_ts',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='tradeanalysis',
            name='symbol',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tradeanalysis',
            name='timeframe',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
    ]
