# Generated by Django 5.2.5 on 2025-08-23 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_alter_tradeanalysis_bar_ts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeanalysis',
            name='bar_ts',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='tradeanalysis',
            name='symbol',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='tradeanalysis',
            name='timeframe',
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
