# Generated by Django 5.2.5 on 2025-08-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_alter_tradeanalysis_bar_ts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderTelemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=64, unique=True)),
                ('quota_usage_pct', models.FloatField(blank=True, null=True)),
                ('key_age_days', models.IntegerField(blank=True, null=True)),
                ('fallback_active', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Provider Telemetry',
                'verbose_name_plural': 'Provider Telemetries',
            },
        ),
    ]
