# Generated by Django 5.2.5 on 2025-08-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_providertelemetry'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('provider_order', models.CharField(default='AllTick', max_length=128)),
                ('ml_blend_weight', models.FloatField(default=0.5)),
                ('autoslowdown_enabled', models.BooleanField(default=True)),
                ('thresholds', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
