# Generated by Django 5.2.5 on 2025-09-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_userpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestionstatus',
            name='backoff_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ingestionstatus',
            name='backoff_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingestionstatus',
            name='in_backoff',
            field=models.BooleanField(default=False),
        ),
    ]
